### ISSUE TITLE
File partial breaks because of locale

### ISSUE THREAD

**Issue by mraaroncruz** [comfy/comfortable-mexican-sofa#175]
If I change line 16 below - below  to

``` ruby
 <div class='file_size'><%= number_to_human_size(file.file_file_size, locale: :en) %></div>
```

it works as expected
I would submit a patch but there are a bunch of ways to hit this.

_ERROR_

```
Completed 500 Internal Server Error in 77ms

ActionView::Template::Error (wrong argument type nil (expected Fixnum)):
    13:       <input type='text' value='<%= file.file.url %>'/>
    14:       <div class='file_type'><%= file.file_content_type %></div>
    15:       <% Rails.logger.info file.file_file_size.class.inspect -%>
    16:       <div class='file_size'><%= number_to_human_size(file.file_file_size) %></div>
    17:     </div>
    18:   </div>
    19: </div>
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.3/lib/action_view/helpers/number_helper.rb:319:in `round'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.3/lib/action_view/helpers/number_helper.rb:319:in `number_with_precision'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.3/lib/action_view/helpers/number_helper.rb:401:in `number_to_human_size'
  vendor/bundle/ruby/1.9.1/gems/comfortable_mexican_sofa-1.6.14/app/views/cms_admin/files/_file.html.erb:16:in `_d41d8cd98f00b204e9800998ecf8427e__vendor_bundle_ruby_______gems_comfortable_mexican_sofa________app_views_cms_admin_files__file_html_erb___2458214366590730765_70246118500820'
```

**Comment by k3rni** [comment]
This just bit me from the other end - I don't want to have an English locale in my app (for good reasons), and the file partial throws an error. Copying that partial to an appropriate place inside the app and removing `locale: :en` helped. Does that still need to be there?

**Comment by GBH** [comment]
As far I understand this should not be an issue anymore per: https://github.com/rails/rails/commit/56627b619cd72c862097c4622e2c9419be2a8a80
