### ISSUE TITLE
Getting a 404 when using more than one site with the same hostname but different paths

### ISSUE THREAD

**Issue by adlersantos** [comfy/comfortable-mexican-sofa#468]
I'm using CMS version 1.12.0 and Rails 4.0.5. 

I mounted the cms to the path `/a` and I created two sites having paths `promos` and `popular`. Thus we expect the two sites to have their root paths at `/a/promos` and `/a/popular`. 

When I create the two sites and navigate to any of the root pages, I get an error that says Site Not Found. But when I delete one of the sites (say the `promos` site) and navigate to the root page of the **one remaining site** (thus `/a/popular`), I get a proper response from the server and the page renders successfully.

I tried playing around with paths and the content serving route. It seems that the routes are working well if only one `Comfy::Cms::Site` exists.

Here's the stack trace for the error when I have more than one site and I navigate to any root page:

```
Started GET "/a/popular/" for 127.0.0.1 at 2014-05-26 12:17:37 +0800
Processing by Comfy::Cms::ContentController#show as HTML
  Parameters: {"cms_path"=>"popular"}
   (0.3ms)  SELECT COUNT(*) FROM "comfy_cms_sites"
  Comfy::Cms::Site Load (0.6ms)  SELECT "comfy_cms_sites".* FROM "comfy_cms_sites" WHERE "comfy_cms_sites"."hostname" = 'localhost:3000'
Completed 404 Not Found in 5ms

ActionController::RoutingError - Site Not Found:
  comfortable_mexican_sofa (1.12.0) app/controllers/comfy/cms/base_controller.rb:26:in `load_cms_site'
  activesupport (4.0.5) lib/active_support/callbacks.rb:417:in `_run__3480373336266725030__process_action__callbacks'
  activesupport (4.0.5) lib/active_support/callbacks.rb:80:in `run_callbacks'
  actionpack (4.0.5) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (4.0.5) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.0.5) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.0.5) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.0.5) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.0.5) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.0.5) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.0.5) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.0.5) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.0.5) lib/abstract_controller/base.rb:136:in `process'
  actionpack (4.0.5) lib/abstract_controller/rendering.rb:44:in `process'
  actionpack (4.0.5) lib/action_controller/metal.rb:195:in `dispatch'
  actionpack (4.0.5) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.0.5) lib/action_controller/metal.rb:231:in `block in action'
  actionpack (4.0.5) lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
  actionpack (4.0.5) lib/action_dispatch/routing/route_set.rb:48:in `call'
  actionpack (4.0.5) lib/action_dispatch/journey/router.rb:71:in `block in call'
  actionpack (4.0.5) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.0.5) lib/action_dispatch/routing/route_set.rb:674:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.5.2) lib/rack/etag.rb:23:in `call'
  rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
  rack (1.5.2) lib/rack/head.rb:11:in `call'
  actionpack (4.0.5) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.0.5) lib/action_dispatch/middleware/flash.rb:241:in `call'
  rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.0.5) lib/action_dispatch/middleware/cookies.rb:486:in `call'
  activerecord (4.0.5) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.0.5) lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
  activerecord (4.0.5) lib/active_record/migration.rb:373:in `call'
  actionpack (4.0.5) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.0.5) lib/active_support/callbacks.rb:373:in `_run__1935395809516368815__call__callbacks'
  activesupport (4.0.5) lib/active_support/callbacks.rb:80:in `run_callbacks'
  actionpack (4.0.5) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.0.5) lib/action_dispatch/middleware/reloader.rb:64:in `call'
  actionpack (4.0.5) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:56:in `call'
  actionpack (4.0.5) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.0.5) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.0.5) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.0.5) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.0.5) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.0.5) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.0.5) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.0.5) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.0.5) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.0.5) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  actionpack (4.0.5) lib/action_dispatch/middleware/static.rb:64:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  railties (4.0.5) lib/rails/engine.rb:511:in `call'
  railties (4.0.5) lib/rails/application.rb:97:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  rack (1.5.2) lib/rack/content_length.rb:14:in `call'
  rack (1.5.2) lib/rack/handler/webrick.rb:60:in `service'
  /Users/adlersantos/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
  /Users/adlersantos/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
  /Users/adlersantos/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```

Thanks in advance for any help! :)

**Comment by GBH** [comment]
I believe i merged PR that deals with this
