### ISSUE TITLE
Can't export

### ISSUE THREAD

**Issue by catmando** [comfy/comfortable-mexican-sofa#495]
I get the below error when exporting.  (comfortable_mexican_sofa (1.12.1))

I did some digging and it doesn't seem that any of my blocks have a page reference.

There was a recent change adding the offending lines of code, perhaps that is the problem?

````ruby
NoMethodError: undefined method `page' for #<Comfy::Cms::Block:0x007fb1451fec50>                                                                                                 
/home/action/.gem/ruby/2.1.1/gems/activemodel-4.1.0/lib/active_model/attribute_methods.rb:435:in `method_missing'                                                                
/home/action/.gem/ruby/2.1.1/gems/activerecord-4.1.0/lib/active_record/attribute_methods.rb:206:in `method_missing'                                                              
/home/action/.gem/ruby/2.1.1/gems/comfortable_mexican_sofa-1.12.1/lib/comfortable_mexican_sofa/fixture/file.rb:54:in `block in export!'                                          
/home/action/.gem/ruby/2.1.1/gems/activerecord-4.1.0/lib/active_record/relation/delegation.rb:46:in `each'                                                                       
/home/action/.gem/ruby/2.1.1/gems/activerecord-4.1.0/lib/active_record/relation/delegation.rb:46:in `each'                                                                       
/home/action/.gem/ruby/2.1.1/gems/comfortable_mexican_sofa-1.12.1/lib/comfortable_mexican_sofa/fixture/file.rb:51:in `export!'                                                   
/home/action/.gem/ruby/2.1.1/gems/comfortable_mexican_sofa-1.12.1/lib/comfortable_mexican_sofa/fixture.rb:72:in `export!'                                                        
/home/action/.gem/ruby/2.1.1/gems/comfortable_mexican_sofa-1.12.1/lib/tasks/comfortable_mexican_sofa.rake:32:in `block (3 levels) in <top (required)>'

**Comment by JoppeSchwartz** [comment]
Thanks @glance - I had the same problem, and your solution worked nicely. Are you going to submit a PR for this?

**Comment by glance-** [comment]
Nope. You can do it.

**Comment by GBH** [comment]
This is fixed in master
