### ISSUE TITLE
'Asset filtered out and will not be served' - on fresh install.

### ISSUE THREAD

**Issue by bradchaiken** [comfy/comfortable-mexican-sofa#585]
Getting the following error on a fresh app install. 

I am following these install instructions: https://github.com/comfy/comfortable-mexican-sofa/wiki/Installation-and-Quick-Start-Guide

NOTE: I did notice the following commit from 4 - days ago and am wondering if this is the cause of the break (icon_page.gif): 
https://github.com/comfy/comfortable-mexican-sofa/commit/fa1465eed6b4ac598935c3abe837b7425d8c71ae

```
Started GET "/admin/sites/new" for ::1 at 2015-01-22 09:57:07 -0500
Processing by Comfy::Admin::Cms::SitesController#new as HTML
  Rendered /Users/bradchaiken/.rvm/gems/ruby-2.1.5/gems/comfortable_mexican_sofa-1.12.6/app/views/comfy/admin/cms/partials/_site_form_before.html.haml (0.8ms)
  Rendered /Users/bradchaiken/.rvm/gems/ruby-2.1.5/gems/comfortable_mexican_sofa-1.12.6/app/views/comfy/admin/cms/partials/_site_form_after.html.haml (0.8ms)
  Rendered /Users/bradchaiken/.rvm/gems/ruby-2.1.5/gems/comfortable_mexican_sofa-1.12.6/app/views/comfy/admin/cms/sites/_form.html.haml (13.8ms)
  Rendered /Users/bradchaiken/.rvm/gems/ruby-2.1.5/gems/comfortable_mexican_sofa-1.12.6/app/views/comfy/admin/cms/sites/new.html.haml within layouts/comfy/admin/cms (20.4ms)
  Rendered /Users/bradchaiken/.rvm/gems/ruby-2.1.5/gems/comfortable_mexican_sofa-1.12.6/app/views/layouts/comfy/admin/cms/_head.html.haml (1629.7ms)
Completed 500 Internal Server Error in 1667ms

ActionView::Template::Error (Asset filtered out and will not be served: add `Rails.application.config.assets.precompile += %w( comfy/admin/cms/icon_page.gif )` to `config/initializers/assets.rb` and restart your server
  (in /Users/bradchaiken/.rvm/gems/ruby-2.1.5/gems/comfortable_mexican_sofa-1.12.6/app/assets/stylesheets/comfy/admin/cms/application.sass)):
    3:   %title= ComfortableMexicanSofa.config.cms_title
    4:   = csrf_meta_tag
    5: 
    6:   = stylesheet_link_tag     'comfy/admin/cms/application', 'data-turbolinks-track' => true
    7:   = javascript_include_tag  'comfy/admin/cms/application', 'data-turbolinks-track' => true
    8: 
    9:   - if @site && @site.persisted?
  sprockets-rails (2.2.3) lib/sprockets/rails/helper.rb:193:in `check_errors_for'
  sprockets-rails (2.2.3) lib/sprockets/rails/helper.rb:89:in `asset_path'
  actionview (4.2.0) lib/action_view/helpers/asset_url_helper.rb:292:in `image_path'
  sprockets (2.12.3) lib/sprockets/sass_functions.rb:14:in `image_path'
  sass (3.4.10) lib/sass/script/tree/funcall.rb:140:in `_perform'
  sass (3.4.10) lib/sass/script/tree/node.rb:50:in `perform'
  sass (3.4.10) lib/sass/script/tree/funcall.rb:170:in `perform_arg'
  sass (3.4.10) lib/sass/script/tree/funcall.rb:124:in `block in _perform'
  sass (3.4.10) lib/sass/script/tree/funcall.rb:124:in `each'
  sass (3.4.10) lib/sass/script/tree/funcall.rb:124:in `each_with_index'
  sass (3.4.10) lib/sass/script/tree/funcall.rb:124:in `each'
  sass (3.4.10) lib/sass/script/tree/funcall.rb:124:in `map'
  sass (3.4.10) lib/sass/script/tree/funcall.rb:124:in `_perform'
  sass (3.4.10) lib/sass/script/tree/node.rb:50:in `perform'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:394:in `visit_prop'
  sass (3.4.10) lib/sass/tree/visitors/base.rb:36:in `visit'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:158:in `block in visit'
  sass (3.4.10) lib/sass/stack.rb:79:in `block in with_base'
  sass (3.4.10) lib/sass/stack.rb:115:in `with_frame'
  sass (3.4.10) lib/sass/stack.rb:79:in `with_base'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:158:in `visit'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:430:in `block (2 levels) in visit_rule'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:430:in `map'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:430:in `block in visit_rule'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:179:in `with_environment'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:428:in `visit_rule'
  sass (3.4.10) lib/sass/tree/visitors/base.rb:36:in `visit'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:158:in `block in visit'
  sass (3.4.10) lib/sass/stack.rb:79:in `block in with_base'
  sass (3.4.10) lib/sass/stack.rb:115:in `with_frame'
  sass (3.4.10) lib/sass/stack.rb:79:in `with_base'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:158:in `visit'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:430:in `block (2 levels) in visit_rule'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:430:in `map'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:430:in `block in visit_rule'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:179:in `with_environment'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:428:in `visit_rule'
  sass (3.4.10) lib/sass/tree/visitors/base.rb:36:in `visit'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:158:in `block in visit'
  sass (3.4.10) lib/sass/stack.rb:79:in `block in with_base'
  sass (3.4.10) lib/sass/stack.rb:115:in `with_frame'
  sass (3.4.10) lib/sass/stack.rb:79:in `with_base'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:158:in `visit'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:430:in `block (2 levels) in visit_rule'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:430:in `map'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:430:in `block in visit_rule'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:179:in `with_environment'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:428:in `visit_rule'
  sass (3.4.10) lib/sass/tree/visitors/base.rb:36:in `visit'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:158:in `block in visit'
  sass (3.4.10) lib/sass/stack.rb:79:in `block in with_base'
  sass (3.4.10) lib/sass/stack.rb:115:in `with_frame'
  sass (3.4.10) lib/sass/stack.rb:79:in `with_base'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:158:in `visit'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:325:in `block (2 levels) in visit_import'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:325:in `map'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:325:in `block in visit_import'
  sass (3.4.10) lib/sass/stack.rb:88:in `block in with_import'
  sass (3.4.10) lib/sass/stack.rb:115:in `with_frame'
  sass (3.4.10) lib/sass/stack.rb:88:in `with_import'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:322:in `visit_import'
  sass (3.4.10) lib/sass/tree/visitors/base.rb:36:in `visit'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:158:in `block in visit'
  sass (3.4.10) lib/sass/stack.rb:79:in `block in with_base'
  sass (3.4.10) lib/sass/stack.rb:115:in `with_frame'
  sass (3.4.10) lib/sass/stack.rb:79:in `with_base'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:158:in `visit'
  sass (3.4.10) lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
  sass (3.4.10) lib/sass/tree/visitors/base.rb:52:in `map'
  sass (3.4.10) lib/sass/tree/visitors/base.rb:52:in `visit_children'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:179:in `with_environment'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:166:in `visit_children'
  sass (3.4.10) lib/sass/tree/visitors/base.rb:36:in `block in visit'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:186:in `visit_root'
  sass (3.4.10) lib/sass/tree/visitors/base.rb:36:in `visit'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:157:in `visit'
  sass (3.4.10) lib/sass/tree/visitors/perform.rb:8:in `visit'
  sass (3.4.10) lib/sass/tree/root_node.rb:36:in `css_tree'
  sass (3.4.10) lib/sass/tree/root_node.rb:20:in `render'
  sass (3.4.10) lib/sass/engine.rb:268:in `render'
  sass-rails (5.0.1) lib/sass/rails/template.rb:47:in `evaluate'
  tilt (1.4.1) lib/tilt/template.rb:103:in `render'
  sprockets (2.12.3) lib/sprockets/context.rb:197:in `block in evaluate'
  sprockets (2.12.3) lib/sprockets/context.rb:194:in `each'
  sprockets (2.12.3) lib/sprockets/context.rb:194:in `evaluate'
  sprockets (2.12.3) lib/sprockets/processed_asset.rb:12:in `initialize'
  sprockets (2.12.3) lib/sprockets/base.rb:374:in `new'
  sprockets (2.12.3) lib/sprockets/base.rb:374:in `block in build_asset'
  sprockets (2.12.3) lib/sprockets/base.rb:395:in `circular_call_protection'
  sprockets (2.12.3) lib/sprockets/base.rb:373:in `build_asset'
  sprockets (2.12.3) lib/sprockets/index.rb:94:in `block in build_asset'
  sprockets (2.12.3) lib/sprockets/caching.rb:58:in `cache_asset'
  sprockets (2.12.3) lib/sprockets/index.rb:93:in `build_asset'
  sprockets (2.12.3) lib/sprockets/base.rb:287:in `find_asset'
  sprockets (2.12.3) lib/sprockets/index.rb:61:in `find_asset'
  sprockets (2.12.3) lib/sprockets/bundled_asset.rb:16:in `initialize'
  sprockets (2.12.3) lib/sprockets/base.rb:377:in `new'
  sprockets (2.12.3) lib/sprockets/base.rb:377:in `build_asset'
  sprockets (2.12.3) lib/sprockets/index.rb:94:in `block in build_asset'
  sprockets (2.12.3) lib/sprockets/caching.rb:58:in `cache_asset'
  sprockets (2.12.3) lib/sprockets/index.rb:93:in `build_asset'
  sprockets (2.12.3) lib/sprockets/base.rb:287:in `find_asset'
  sprockets (2.12.3) lib/sprockets/index.rb:61:in `find_asset'
  sprockets (2.12.3) lib/sprockets/environment.rb:75:in `find_asset'
  sprockets (2.12.3) lib/sprockets/base.rb:295:in `[]'
  sprockets-rails (2.2.3) lib/sprockets/rails/helper.rb:230:in `lookup_asset_for_path'
  sprockets-rails (2.2.3) lib/sprockets/rails/helper.rb:190:in `check_errors_for'
  sprockets-rails (2.2.3) lib/sprockets/rails/helper.rb:159:in `block in stylesheet_link_tag'
  sprockets-rails (2.2.3) lib/sprockets/rails/helper.rb:158:in `map'
  sprockets-rails (2.2.3) lib/sprockets/rails/helper.rb:158:in `stylesheet_link_tag'
  comfortable_mexican_sofa (1.12.6) app/views/layouts/comfy/admin/cms/_head.html.haml:6:in `___sers_bradchaiken__rvm_gems_ruby_______gems_comfortable_mexican_sofa________app_views_layouts_comfy_admin_cms__head_html_haml___3094359530158059236_70302132608680'
  actionview (4.2.0) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.0) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.0) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.0) lib/action_view/template.rb:143:in `render'
  actionview (4.2.0) lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
  actionview (4.2.0) lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
  actionview (4.2.0) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.0) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.0) lib/action_view/renderer/partial_renderer.rb:309:in `render'
  actionview (4.2.0) lib/action_view/renderer/renderer.rb:47:in `render_partial'
  actionview (4.2.0) lib/action_view/helpers/rendering_helper.rb:35:in `render'
  haml (4.0.6) lib/haml/helpers/action_view_mods.rb:10:in `block in render_with_haml'
  haml (4.0.6) lib/haml/helpers.rb:89:in `non_haml'
  haml (4.0.6) lib/haml/helpers/action_view_mods.rb:10:in `render_with_haml'
  comfortable_mexican_sofa (1.12.6) app/views/layouts/comfy/admin/cms.html.haml:3:in `___sers_bradchaiken__rvm_gems_ruby_______gems_comfortable_mexican_sofa________app_views_layouts_comfy_admin_cms_html_haml__2513552716365095356_70302143113480'
  actionview (4.2.0) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.0) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.0) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.0) lib/action_view/template.rb:143:in `render'
  actionview (4.2.0) lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
  actionview (4.2.0) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.0) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.0) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.2.0) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.2.0) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.0) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.0) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.0) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.0) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.0) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.0) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
  activesupport (4.2.0) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /Users/bradchaiken/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
  activesupport (4.2.0) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:41:in `block in render'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
  activerecord (4.2.0) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:40:in `render'
  comfortable_mexican_sofa (1.12.6) lib/comfortable_mexican_sofa/render_methods.rb:58:in `render'
  comfortable_mexican_sofa (1.12.6) app/controllers/comfy/admin/cms/sites_controller.rb:17:in `new'
  actionpack (4.2.0) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.0) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
  activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.0) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.0) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.0) lib/action_controller/metal.rb:195:in `dispatch'
  actionpack (4.2.0) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.0) lib/action_controller/metal.rb:236:in `block in action'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:42:in `serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:802:in `call'
  rack (1.6.0) lib/rack/etag.rb:24:in `call'
  rack (1.6.0) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.0) lib/rack/head.rb:13:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.0) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.0) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.0) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
  activerecord (4.2.0) lib/active_record/migration.rb:378:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:18:in `middleware_call'
  web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:13:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.0) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.0) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.0) lib/rails/engine.rb:518:in `call'
  railties (4.2.0) lib/rails/application.rb:164:in `call'
  rack (1.6.0) lib/rack/lock.rb:17:in `call'
  rack (1.6.0) lib/rack/content_length.rb:15:in `call'
  rack (1.6.0) lib/rack/handler/webrick.rb:89:in `service'
  /Users/bradchaiken/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
  /Users/bradchaiken/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
  /Users/bradchaiken/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'


  Rendered /Users/bradchaiken/.rvm/gems/ruby-2.1.5/gems/web-console-2.0.0/lib/action_dispatch/templates/rescues/_source.erb (9.6ms)
  Rendered /Users/bradchaiken/.rvm/gems/ruby-2.1.5/gems/web-console-2.0.0/lib/action_dispatch/templates/rescues/_trace.html.erb (3.3ms)
  Rendered /Users/bradchaiken/.rvm/gems/ruby-2.1.5/gems/web-console-2.0.0/lib/action_dispatch/templates/rescues/_request_and_response.html.erb (0.7ms)
  Rendered /Users/bradchaiken/.rvm/gems/ruby-2.1.5/gems/web-console-2.0.0/lib/action_dispatch/templates/rescues/_web_console.html.erb (0.6ms)
  Rendered /Users/bradchaiken/.rvm/gems/ruby-2.1.5/gems/web-console-2.0.0/lib/action_dispatch/templates/rescues/template_error.html.erb within rescues/layout (30.2ms)
```

```
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.0'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'comfortable_mexican_sofa'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end
```

**Comment by GBH** [comment]
Did you find out what it was? I didn't get the chance to try it out.
