### ISSUE TITLE
Routing error for glyphicons

### ISSUE THREAD

**Issue by agbodike** [comfy/comfortable-mexican-sofa#704]
I'm seeing the following error in my dev environment:

```
ActionController::RoutingError (No route matches [GET] "/assets/comfy/admin/fonts/glyphicons-halflings-regular.ttf"):
  actionpack (4.0.13) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  railties (4.0.13) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.0.13) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.0.13) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.0.13) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.0.13) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.0.13) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.5.5) lib/rack/runtime.rb:17:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  activesupport (4.0.13) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.5.5) lib/rack/lock.rb:17:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/static.rb:84:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  airbrake (4.1.0) lib/airbrake/user_informer.rb:16:in `_call'
  airbrake (4.1.0) lib/airbrake/user_informer.rb:12:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  railties (4.0.13) lib/rails/engine.rb:511:in `call'
  railties (4.0.13) lib/rails/application.rb:97:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack-reverse-proxy (0.4.4) lib/rack/reverse_proxy.rb:16:in `call'
  newrelic_rpm (3.11.1.284) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.5.5) lib/rack/content_length.rb:14:in `call'
  puma (2.11.1) lib/puma/server.rb:507:in `handle_request'
  puma (2.11.1) lib/puma/server.rb:375:in `process_client'
  puma (2.11.1) lib/puma/server.rb:262:in `block in run'
  puma (2.11.1) lib/puma/thread_pool.rb:104:in `call'
  puma (2.11.1) lib/puma/thread_pool.rb:104:in `block in spawn_thread'
```

I have the following at the bottom of my routes.rb:

```
  comfy_route :cms_admin, :path => '/comfy_admin'
  # Make sure this routeset is defined last
  comfy_route :cms, :path => '/cms/', :sitemap => false
```

**Comment by agbodike** [comment]
ping

**Comment by GBH** [comment]
Closing as it's a very old one. Never observed this problem. New CMS doesn't have glyphicons (Bootstrap 4 got rid of them). It's all about AwesomeFont now.
