### ISSUE TITLE
ArgumentError: Invalid route name: 'comfy_cms_:format' Rails 5 Error

### ISSUE THREAD

**Issue by diegomichel** [comfy/comfortable-mexican-sofa#739]
Hello guys,

I'm trying to test comfortable mexican sofa on rails 5 but was unable to run the migrations, it is a clean project just after creating it with rails new and adding the gem to the Gemfile.

Help appreciated, thank you :).
```
rake db:migrate                                                                                                                                          [61/1078]
rake aborted!
ArgumentError: Invalid route name: 'comfy_cms_:format'
/home/novo/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:504:in`add_route'
/home/novo/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/mapper.rb:1699:in `add_route'
/home/novo/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/mapper.rb:1670:in `decomposed_match'
/home/novo/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/mapper.rb:1634:in `block in match'
/home/novo/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/mapper.rb:1617:in `each'
/home/novo/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/mapper.rb:1617:in `match'
/home/novo/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/mapper.rb:722:in `map_method'
/home/novo/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/mapper.rb:680:in `get'
/home/novo/.rvm/gems/ruby-2.3.0/gems/comfortable_mexican_sofa-1.12.2/lib/comfortable_mexican_sofa/routes/cms.rb:16:in `block (2 levels) in comfy_route_cms'
/home/novo/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/mapper.rb:937:in `block (2 levels) in namespace'
/home/novo/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/mapper.rb:859:in `scope'
/home/novo/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/mapper.rb:937:in `block in namespace'
/home/novo/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/mapper.rb:1922:in `path_scope'
/home/novo/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/mapper.rb:936:in `namespace'
/home/novo/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/mapper.rb:1548:in `namespace'
/home/novo/.rvm/gems/ruby-2.3.0/gems/comfortable_mexican_sofa-1.12.2/lib/comfortable_mexican_sofa/routes/cms.rb:5:in `block in comfy_route_cms'
/home/novo/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/mapper.rb:859:in `scope'
/home/novo/.rvm/gems/ruby-2.3.0/gems/comfortable_mexican_sofa-1.12.2/lib/comfortable_mexican_sofa/routes/cms.rb:4:in `comfy_route_cms'
/home/novo/.rvm/gems/ruby-2.3.0/gems/comfortable_mexican_sofa-1.12.2/lib/comfortable_mexican_sofa/routing.rb:6:in `comfy_route'
/home/novo/projects/cms_test/config/routes.rb:5:in `block in <top (required)>'
/home/novo/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:389:in`instance_exec'
/home/novo/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:389:in`eval_block'
/home/novo/.rvm/gems/ruby-2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:371:in`draw'
/home/novo/projects/cms_test/config/routes.rb:1:in `<top (required)>'
/home/novo/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
/home/novo/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `block in load'
/home/novo/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
/home/novo/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
/home/novo/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
/home/novo/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:40:in `each'
/home/novo/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:40:in `load_paths'
/home/novo/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:16:in `reload!'
/home/novo/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:26:in `block in updater'
/home/novo/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/file_update_checker.rb:77:in `execute'
/home/novo/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:27:in `updater'
/home/novo/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
/home/novo/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/application/finisher.rb:119:in `block in <module:Finisher>'
/home/novo/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `instance_exec'
/home/novo/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `run'
/home/novo/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/novo/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:54:in `run_initializers'
/home/novo/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/application.rb:352:in `initialize!'
/home/novo/projects/cms_test/config/environment.rb:5:in `<top (required)>'
/home/novo/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
/home/novo/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
/home/novo/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
/home/novo/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
/home/novo/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/application.rb:328:in `require_environment!'
/home/novo/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.1/lib/rails/application.rb:448:in `block in run_tasks_blocks'
/home/novo/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
```
Gemfile

```
gem 'comfortable_mexican_sofa', '~> 1.12.0'

```

routes.rb
```
  1 Rails.application.routes.draw do
  2   comfy_route :cms_admin, :path => '/admin'
  3
  4   # Make sure this routeset is defined last
  5   comfy_route :cms, :path => '/', :sitemap => false
  6
  7   # For details on the DSL available within this file, see http://guides.rubyonr    ails.org/routing.html
  8 end

```

```
rails -v
Rails 5.0.0.1

gem list|grep comforta
comfortable_mexican_sofa (1.12.2)
```

**Comment by GBH** [comment]
Try using master branch directly. Gem is not running on Rails 5 yet.

**Comment by diegomichel** [comment]
Alright thanks for the info Oleg

**Comment by Seaborg** [comment]
Hi Oleg, Any time frame for pushing the gem to rails 5? Also what about bootstrap update?
perhaps:

bootstrap-sass (= 3.3.7)

**Comment by jfeust** [comment]
+1

**Comment by GBH** [comment]
I kinda fucked up my rubygems.org account. Will release 1.12.10 that works with Rails 5 as soon as that's cleared up.

**Comment by GBH** [comment]
New gem is published. Should clear up Rails 5 issues.
