### ISSUE TITLE
rails5.1 route error

### ISSUE THREAD

**Issue by zires** [comfy/comfortable-mexican-sofa#760]
Ambigous route definition. Both :path and the route path where specified as strings. (ArgumentError)

**Comment by GBH** [comment]
Right now CMS works with Rails 4.2 and Rails 5.0 (with tons of deprecation messages). Rails 5.1 acts on those deprecations. To fix everything means completely dropping support for Rails 4. This is something I need to work on.

**Comment by Daniel-ltw** [comment]
https://github.com/comfy/comfortable-mexican-sofa/issues/738

Like I said. You need someone to help you, as comfy is getting bigger with wider audience.

**Comment by GBH** [comment]
I'd welcome an interim fork of CMS that works with Rails 5.1. That would be an enormous help.

I'm thinking doing a major rewrite soon for version 2.0. There are just too many changes in Rails 5.1 to continue patching existing codebase. But if somebody could do some initial work to figure out wtf is happening with asset files these days, that would be amazing.

**Comment by asadakbar** [comment]
Don't mean to add pressure to this issue, but I was hoping to find out if progress has been made to make comfy compatible with rails 5.1. We are evaluating options for cms's and would love to dive into comfy as an option for a rather large rails 5.1 app.

**Comment by joeljackson** [comment]
Worth noting that this works on rails 5.1 for me by just allowing it to use rails 5.1. I haven't run the tests though, so although it works for my purposes making no promises.

Will take a look at specs and if they're not a disaster see if I can merge something in.

**Comment by lthurston** [comment]
Does anyone have a fork for 5.1 that's mostly working? I've found that -- so far -- only minor changes are needed to get the admin parts working, but I've been modifying the bundle-installed files just to see if if it was remotely viable. Before I fork it myself, I thought I'd ask. :)

**Comment by joeljackson** [comment]
@lthurston This is working for me: https://github.com/joeljackson/comfortable-mexican-sofa

I didn't change anything but the rails version required. But for what I'm using it for it is rendering pages just fine and the admin section is doing what it's supposed to do.

**Comment by grichardomi** [comment]
Is there is fix for this : Ambigous route definition. Both :path and the route path where specified as strings. (ArgumentError)?

**Comment by GBH** [comment]
Can somebody please post a stack trace? I'm working on Rails 5.2 update and I'm not seeing anything like this with current routes.

**Comment by loyaruarutoitsu** [comment]
```
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rails aborted!
ArgumentError: Ambigous route definition. Both :path and the route path where specified as strings.
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/routing/mapper.rb:1852:in `block in map_match'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/routing/mapper.rb:1849:in `each'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/routing/mapper.rb:1849:in `map_match'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/routing/mapper.rb:1597:in `match'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/routing/mapper.rb:730:in `map_method'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/routing/mapper.rb:691:in `get'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/comfortable_mexican_sofa-1.12.2/lib/comfortable_mexican_sofa/routes/cms.rb:16:in `block (2 levels) in comfy_route_cms'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/routing/mapper.rb:935:in `block (2 levels) in namespace'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/routing/mapper.rb:866:in `scope'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/routing/mapper.rb:935:in `block in namespace'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/routing/mapper.rb:1820:in `path_scope'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/routing/mapper.rb:934:in `namespace'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/routing/mapper.rb:1546:in `namespace'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/comfortable_mexican_sofa-1.12.2/lib/comfortable_mexican_sofa/routes/cms.rb:5:in `block in comfy_route_cms'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/routing/mapper.rb:866:in `scope'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/comfortable_mexican_sofa-1.12.2/lib/comfortable_mexican_sofa/routes/cms.rb:4:in `comfy_route_cms'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/comfortable_mexican_sofa-1.12.2/lib/comfortable_mexican_sofa/routing.rb:6:in `comfy_route'
/home/colin/RubymineProjects/pro/config/routes.rb:5:in `block in <top (required)>'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/routing/route_set.rb:426:in `instance_exec'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/routing/route_set.rb:426:in `eval_block'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/routing/route_set.rb:408:in `draw'
/home/colin/RubymineProjects/pro/config/routes.rb:1:in `<top (required)>'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `block in load'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/application/routes_reloader.rb:55:in `block in load_paths'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/application/routes_reloader.rb:55:in `each'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/application/routes_reloader.rb:55:in `load_paths'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/application/routes_reloader.rb:18:in `reload!'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/application/routes_reloader.rb:41:in `block in updater'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/file_update_checker.rb:81:in `execute'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/application/routes_reloader.rb:42:in `updater'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/application/routes_reloader.rb:31:in `execute_if_updated'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/application/finisher.rb:128:in `block in <module:Finisher>'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `instance_exec'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `run'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/initializable.rb:59:in `block in run_initializers'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/initializable.rb:58:in `run_initializers'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/application.rb:353:in `initialize!'
/home/colin/RubymineProjects/pro/config/environment.rb:5:in `<top (required)>'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `block in require'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/application.rb:329:in `require_environment!'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/application.rb:445:in `block in run_tasks_blocks'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.1.0/lib/rake/task.rb:251:in `block in execute'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.1.0/lib/rake/task.rb:251:in `each'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.1.0/lib/rake/task.rb:251:in `execute'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.1.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.1.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.1.0/lib/rake/task.rb:217:in `block in invoke_prerequisites'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.1.0/lib/rake/task.rb:215:in `each'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.1.0/lib/rake/task.rb:215:in `invoke_prerequisites'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.1.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.1.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.1.0/lib/rake/task.rb:181:in `invoke'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.1.0/lib/rake/application.rb:153:in `invoke_task'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.1.0/lib/rake/application.rb:109:in `block (2 levels) in top_level'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.1.0/lib/rake/application.rb:109:in `each'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.1.0/lib/rake/application.rb:109:in `block in top_level'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.1.0/lib/rake/application.rb:118:in `run_with_threads'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.1.0/lib/rake/application.rb:103:in `top_level'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.1.0/lib/rake/application.rb:179:in `standard_exception_handling'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/command.rb:46:in `invoke'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
/home/colin/RubymineProjects/pro/bin/rails:9:in `require'
/home/colin/RubymineProjects/pro/bin/rails:9:in `<top (required)>'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/binstub.rb:25:in `load'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/binstub.rb:25:in `<top (required)>'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
/home/colin/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
/home/colin/RubymineProjects/pro/bin/spring:15:in `<top (required)>'
-e:1:in `load'
-e:1:in `<main>'
Tasks: TOP => db:migrate => environment

Process finished with exit code 1
```

**Comment by GBH** [comment]
@loyaruarutoitsu That's CMS 1.12.2. Upgrade to the latest as routing changed since then. No wonder I could not see this. 1.12.10 doesn't have this problem even in Rails 5.2

Please re-open if there's still some routing issues with current version.

**Comment by tadman** [comment]
1.12.10 is locked to Rails < 5.1, so is there a way to bypass that without a fork?

**Comment by GBH** [comment]
5.1 breaks test suite completely. I can't guarantee that it will work (it might). So forking is better. Or fix tests with a PR.

**Comment by tadman** [comment]
An unlocked `master` branch or something of the stort with the implied "use at own risk" would side-step the fork part. If you're working towards 5.1+ compatibility, that's one place to start, then we can pull against that spec.

**Comment by GBH** [comment]
@tadman I made rails5.1 branch: https://github.com/comfy/comfortable-mexican-sofa/tree/rails5.1 (tests all bomb of course). Did you inherit an app with it that needs upgrading or something?

**Comment by tadman** [comment]
It's a 4.2 app that I want to bump to 5.1 just to keep it current.
