### ISSUE TITLE
Comfy gem cause asset:precompile to fail on heroku

### ISSUE THREAD

**Issue by Br3nda** [comfy/comfortable-mexican-sofa#864]
### Expected behaviour
the app should deploy to Heroku.

### Actual behaviour
uglifier throws errors on rake assets:precompile, halting the deploy on Heroku.
If I remove ComfyMexicanSofa from the gem bundle, the errors are gone, and the app deploys.

I've followed the instructions on https://github.com/comfy/comfortable-mexican-sofa/issues/832 

and put this in production.rb
```
config.assets.js_compressor = Uglifier.new(harmony: true)
```

but we're still getting the error at deploy on Heroku
```
       rake aborted!
       Uglifier::Error: Unexpected token: punc ()). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).
       /tmp/build_ff0c4ce9a0c440fff142d153051b5cc7/vendor/bundle/ruby/2.6.0/gems/uglifier-4.1.20/lib/uglifier.rb:234:in `parse_result'
       /tmp/build_ff0c4ce9a0c440fff142d153051b5cc7/vendor/bundle/ruby/2.6.0/gems/uglifier-4.1.20/lib/uglifier.rb:216:in `run_uglifyjs'
       /tmp/build_ff0c4ce9a0c440fff142d153051b5cc7/vendor/bundle/ruby/2.6.0/gems/uglifier-4.1.20/lib/uglifier.rb:168:in `compile'
       /tmp/build_ff0c4ce9a0c440fff142d153051b5cc7/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/uglifier_compressor.rb:53:in `call'
       /tmp/build_ff0c4ce9a0c440fff142d153051b5cc7/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/uglifier_compressor.rb:28:in `call'
```

These errors go away when ComfyMexicanSofa is removed from the gem bundle

### Steps to reproduce
Things that help:

* Describe issue in detail.
* Add relevant code snippets.
* Create a failing test case.

### System configuration
**Rails version**: 5.2
**CMS version**: 2.0
**Ruby version**: 2.6

PR, where i'm trying to resolve this deploy error, is here
https://github.com/Growstuff/growstuff/pull/1782

**Comment by GBH** [comment]
Having `config.assets.js_compressor = Uglifier.new(harmony: true)` seems like a correct thing to do. But looking at the error it seems like that setting didn't stick.

```
Uglifier::Error: Unexpected token: punc ()). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).
```

Seems like an application config issue.
