### ISSUE TITLE
comfy:cms_seeds:import undefined method `original_filename'

### ISSUE THREAD

**Issue by mdagraca** [comfy/comfortable-mexican-sofa#909]
*Note:* For general questions and feature requests please leave a message
on Gitter: https://gitter.im/comfy/comfortable-mexican-sofa

### Expected behavior 
Import files in db/cms_seeds/site/files
The files folder has only jpg files, not yml files

### Actual behavior
undefined method `original_filename'

### Steps to reproduce
`NoMethodError: undefined method `original_filename' for #<Hash:0x00007ff3ef32ff60>
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/comfortable_mexican_sofa-2.0.19/app/models/comfy/cms/file.rb:54:in `assign_label'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:179:in `block (2 levels) in halting_and_conditional'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:605:in `catch'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:605:in `block in default_terminator'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:180:in `block in halting_and_conditional'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:513:in `each'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:513:in `invoke_before'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:131:in `run_callbacks'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:816:in `_run_validation_callbacks'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activemodel-5.2.4.1/lib/active_model/validations/callbacks.rb:118:in `run_validations!'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activemodel-5.2.4.1/lib/active_model/validations.rb:339:in `valid?'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.4.1/lib/active_record/validations.rb:67:in `valid?'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.4.1/lib/active_record/validations.rb:84:in `perform_validations'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.4.1/lib/active_record/validations.rb:46:in `save'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.4.1/lib/active_record/transactions.rb:310:in `block (2 levels) in save'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.4.1/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.4.1/lib/active_record/transactions.rb:212:in `transaction'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.4.1/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.4.1/lib/active_record/transactions.rb:310:in `block in save'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.4.1/lib/active_record/transactions.rb:325:in `rollback_active_record_state!'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.4.1/lib/active_record/transactions.rb:309:in `save'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.4.1/lib/active_record/suppressor.rb:44:in `save'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/comfortable_mexican_sofa-2.0.19/lib/comfortable_mexican_sofa/seeds/file/importer.rb:46:in `block in import!'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/comfortable_mexican_sofa-2.0.19/lib/comfortable_mexican_sofa/seeds/file/importer.rb:12:in `each'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/comfortable_mexican_sofa-2.0.19/lib/comfortable_mexican_sofa/seeds/file/importer.rb:12:in `import!'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/comfortable_mexican_sofa-2.0.19/lib/comfortable_mexican_sofa/seeds.rb:36:in `block in import!'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/comfortable_mexican_sofa-2.0.19/lib/comfortable_mexican_sofa/seeds.rb:34:in `each'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/comfortable_mexican_sofa-2.0.19/lib/comfortable_mexican_sofa/seeds.rb:34:in `import!'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/comfortable_mexican_sofa-2.0.19/lib/tasks/cms_seeds.rake:18:in `block (3 levels) in <top (required)>'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:279:in `block in execute'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:279:in `each'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:279:in `execute'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
/Users/mariela/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/Users/mariela/.rbenv/versions/2.5.3/bin/rake:23:in `load'
/Users/mariela/.rbenv/versions/2.5.3/bin/rake:23:in `<main>'
Tasks: TOP => comfy:cms_seeds:import`

### System configuration
**Rails version**:
Rails 5.2.1
**CMS version**:
comfortable_mexican_sofa (2.0.17)
**Ruby version**:
ruby 2.5.3

**Comment by LetianChen** [comment]
I also ran in to this issue. Any updates on it?
