### ISSUE TITLE
Ruby 3 Support

### ISSUE THREAD

**Issue by rgaufman** [comfy/comfortable-mexican-sofa#947]
*Note:* For general questions and feature requests please leave a message
on Gitter: https://gitter.im/comfy/comfortable-mexican-sofa

### Expected behavior
Should work

### Actual behavior
```
MacBook-Pro-2.local ➜  t-website git:(master) ✗ rails s
=> Booting Puma
=> Rails 6.1.4.1 application starting in development
=> Run `bin/rails server --help` for more startup options
Exiting
/opt/homebrew/lib/ruby/gems/3.0.0/bundler/gems/comfortable-mexican-sofa-8f7e425a06ac/lib/comfortable_mexican_sofa/routes/cms_admin.rb:5:in `comfy_route_cms_admin': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from /opt/homebrew/lib/ruby/gems/3.0.0/bundler/gems/comfortable-mexican-sofa-8f7e425a06ac/lib/comfortable_mexican_sofa/routing.rb:9:in `comfy_route'
	from /Users/hackeron/Development/t-website/config/routes.rb:2:in `block in <main>'
```

### Steps to reproduce
Install Ruby 3.0.2

### System configuration
**Rails version**: 6.1.4.1

**CMS version**: git master (fetched 2021-12-04)

**Ruby version**: 3.0.2

**Comment by mountaindog** [comment]
Hi @rgaufman - I experienced the same thing trying to get Comfy/CMS to work with Ruby 3.x.x.. Unfortunately, I don't think Comfy/CMS is being maintained. 👎

**Comment by AdnanTheExcellent** [comment]
check out https://github.com/restarone/comfortable-mexican-sofa

**Comment by 0vermore** [comment]
> check out https://github.com/restarone/comfortable-mexican-sofa

man, you saved me, thank you very much!

**Comment by CloCkWeRX** [comment]
Might need to open up the issue tracker on that fork.

```
DEPRECATION WARNING: TimeWithZone#to_s(:date) is deprecated. Please use TimeWithZone#to_fs(:date) instead. (called from render at /home/runner/work/growstuff/growstuff/vendor/bundle/ruby/3.1.0/bundler/gems/comfortable-mexican-sofa-456fb8507e96/lib/comfortable_mexican_sofa/render_methods.rb:59)
```
